// Generated by CoffeeScript 1.6.3
var app, loadSubredditData;

app = new Vue({
  el: "#app",
  data: {
    activeSubreddit: "all",
    subredditsList: ["all", "askreddit", "starbound"],
    subreddits: {}
  },
  methods: {
    selectSubreddit: function(e) {
      this.activeSubreddit = e.el.innerText.toLowerCase();
      app.$emit("subreddit switch", e.el.innerText.toLowerCase());
    }
  }
});

loadSubredditData = function() {
  var args;
  args = Array.prototype.slice.call(arguments);
  return args.forEach(function(value) {
    return reqwest({
      url: "http://api.reddit.com/r/" + value.toLowerCase() + ".json",
      method: "GET",
      type: "jsonp",
      jsonpCallback: "jsonp",
      success: function(res) {
        app.subreddits[value] = res.data.children.map(function(item) {
          return item.data;
        });
        return app.$emit("subreddit load data", value.toLowerCase());
      }
    });
  });
};

loadSubredditData("all", "askreddit", "starbound");

app.$on("subreddit switch", function(subreddit) {
  console.log("Switching to /r/" + subreddit);
});

app.$on("subreddit load data", function(subreddit) {
  console.log("Loading data for /r/" + subreddit);
});
